# Generated by Django 3.1.4 on 2021-01-06 16:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('isbn_number', models.CharField(max_length=13, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('publication_date', models.DateField(blank=True, default=None, null=True)),
                ('number_of_pages', models.IntegerField(blank=True, default=None, null=True)),
                ('cover_link', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('publication_language', models.CharField(max_length=150)),
            ],
        ),
    ]
